/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustedContactsRouteImport } from './routes/trusted-contacts'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SafetyResourcesRouteImport } from './routes/safety-resources'
import { Route as ReportIncidentRouteImport } from './routes/report-incident'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CyberSafetyRouteImport } from './routes/cyber-safety'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TrustedContactsRoute = TrustedContactsRouteImport.update({
  id: '/trusted-contacts',
  path: '/trusted-contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyResourcesRoute = SafetyResourcesRouteImport.update({
  id: '/safety-resources',
  path: '/safety-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIncidentRoute = ReportIncidentRouteImport.update({
  id: '/report-incident',
  path: '/report-incident',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberSafetyRoute = CyberSafetyRouteImport.update({
  id: '/cyber-safety',
  path: '/cyber-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cyber-safety': typeof CyberSafetyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report-incident': typeof ReportIncidentRoute
  '/safety-resources': typeof SafetyResourcesRoute
  '/sos': typeof SosRoute
  '/trusted-contacts': typeof TrustedContactsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cyber-safety': typeof CyberSafetyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report-incident': typeof ReportIncidentRoute
  '/safety-resources': typeof SafetyResourcesRoute
  '/sos': typeof SosRoute
  '/trusted-contacts': typeof TrustedContactsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cyber-safety': typeof CyberSafetyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report-incident': typeof ReportIncidentRoute
  '/safety-resources': typeof SafetyResourcesRoute
  '/sos': typeof SosRoute
  '/trusted-contacts': typeof TrustedContactsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cyber-safety'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/report-incident'
    | '/safety-resources'
    | '/sos'
    | '/trusted-contacts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cyber-safety'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/report-incident'
    | '/safety-resources'
    | '/sos'
    | '/trusted-contacts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cyber-safety'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/report-incident'
    | '/safety-resources'
    | '/sos'
    | '/trusted-contacts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CyberSafetyRoute: typeof CyberSafetyRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportIncidentRoute: typeof ReportIncidentRoute
  SafetyResourcesRoute: typeof SafetyResourcesRoute
  SosRoute: typeof SosRoute
  TrustedContactsRoute: typeof TrustedContactsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trusted-contacts': {
      id: '/trusted-contacts'
      path: '/trusted-contacts'
      fullPath: '/trusted-contacts'
      preLoaderRoute: typeof TrustedContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-resources': {
      id: '/safety-resources'
      path: '/safety-resources'
      fullPath: '/safety-resources'
      preLoaderRoute: typeof SafetyResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-incident': {
      id: '/report-incident'
      path: '/report-incident'
      fullPath: '/report-incident'
      preLoaderRoute: typeof ReportIncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-safety': {
      id: '/cyber-safety'
      path: '/cyber-safety'
      fullPath: '/cyber-safety'
      preLoaderRoute: typeof CyberSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CyberSafetyRoute: CyberSafetyRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportIncidentRoute: ReportIncidentRoute,
  SafetyResourcesRoute: SafetyResourcesRoute,
  SosRoute: SosRoute,
  TrustedContactsRoute: TrustedContactsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
